# Use docker compose v2 for non swarm deployments
# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.4'

services:

  nginx:
    command: sh -c "
      echo 'Starting static webserver at http://127.0.0.1:8080/'
      && nginx -g 'daemon off;'
      "
    # https://hub.docker.com/_/nginx
    image: 'nginx:alpine'
    ports:
      - '8080:80'
    restart: on-failure
    volumes:
      - './docs/:/usr/share/nginx/html:ro'
      - './nginx-conf.d/:/etc/nginx/conf.d:ro'
